// READ-ONLY single-source-of-truth regenerator for Phone Assured (PA-AMZN).
// Prints the validated DB baseline (table counts, inventory, ad-engine/review recency).
// No writes. Pairs with confabulator/validated-data-baseline-2026-06-29.md.
// Anti-staleness: this re-pulls live so the doc's "live data" section can be refreshed
// instead of trusting copied numbers (research-discipline.md).
import { createClient } from '@libsql/client';
import { readFileSync } from 'node:fs';

const env = Object.fromEntries(
  readFileSync('.env.local', 'utf8').split('\n')
    .filter(l => l && !l.startsWith('#') && l.includes('='))
    .map(l => { const i = l.indexOf('='); return [l.slice(0, i).trim(), l.slice(i + 1).trim().replace(/^["']|["']$/g, '')]; })
);
const c = createClient({ url: env.DATABASE_URL, authToken: env.DATABASE_AUTH_TOKEN });

const tables = (await c.execute(`SELECT name FROM sqlite_master WHERE type='table' ORDER BY name`)).rows.map(r => r.name);

console.log('# Phone Assured — validated DB baseline (read-only)');
console.log('# Generated by scripts/baseline.mjs. No writes performed.\n');

console.log('## Table row counts');
for (const t of tables) {
  try { const n = (await c.execute(`SELECT COUNT(*) n FROM "${t}"`)).rows[0].n; console.log(`  ${t.padEnd(20)} ${n}`); }
  catch (e) { console.log(`  ${t.padEnd(20)} ERR ${e.message}`); }
}

if (tables.includes('inventory')) {
  console.log('\n## Inventory (FBA on-hand by SKU)');
  const r = await c.execute(`SELECT sku, asin, quantity_fba, quantity_inbound, days_of_supply, amazon_alert FROM inventory ORDER BY quantity_fba DESC`);
  console.log('  SKU                  ASIN         FBA  INBND  DoS   ALERT');
  let inStock = 0, oos = 0;
  for (const row of r.rows) {
    const q = Number(row.quantity_fba) || 0;
    if (q > 0) inStock++; else oos++;
    console.log(`  ${String(row.sku).padEnd(20)} ${String(row.asin).padEnd(12)} ${String(q).padStart(4)} ${String(row.quantity_inbound ?? '').padStart(6)} ${String(row.days_of_supply ?? '').padStart(5)}  ${row.amazon_alert ?? ''}`);
  }
  console.log(`  -> ${inStock} SKU(s) in stock, ${oos} at zero FBA`);
}

const recency = async (table) => {
  if (!tables.includes(table)) return;
  const cols = (await c.execute(`PRAGMA table_info(${table})`)).rows.map(r => r.name);
  const tcol = cols.find(x => /run_at|requested_at|sent_at|created_at|_at$|date|ts/i.test(x));
  if (!tcol) return;
  const r = await c.execute(`SELECT substr(${tcol},1,10) d, COUNT(*) n FROM ${table} GROUP BY d ORDER BY d DESC LIMIT 8`);
  console.log(`\n## ${table} by day (newest first, via ${tcol})`);
  for (const row of r.rows) console.log(`  ${row.d}: ${row.n}`);
};
await recency("ad_engine_log");
await recency("review_requests");

console.log('\n## Note');
console.log('  campaigns/keywords/hourly_snapshots/bid_changes/search_terms = 0 is EXPECTED:');
console.log('  the live ad engine reads from the Ads API at run time, not from these tables');
console.log('  (see memory ad-engine-which-one-runs / sales-drop-root-cause). Not the drop cause.');
