#!/usr/bin/env node
// READ-ONLY ship-plan generator. Reads git only (no checkout, no merge, no push).
// Turns every unmerged local branch into a reviewable merge sequence:
//   - collapses ancestry stacks to their tip (merge the tip, it subsumes the rest)
//   - trial-merges each tip into main (git merge-tree --write-tree) and labels the
//     result clean / doc-only / CODE-CONFLICT (so trivial journal re-appends aren't
//     mistaken for real conflicts)
//   - flags code files >1 unit touches (the ad-engine.ts collision risk, regenerable)
// Output: confabulator/ship-plan-<today>.md  (pass a YYYY-MM-DD arg to date it)
//
// Mirrors the tested src/lib/ship-plan.ts (same script<->lib split as margin-model).
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { register } from "node:module";
import { pathToFileURL } from "node:url";

// Load the TS lib without a build step (Node 22+ strips types via tsx-less loader).
let lib;
try {
  lib = await import("../src/lib/ship-plan.ts");
} catch {
  register("tsx/esm", pathToFileURL("./"));
  lib = await import("../src/lib/ship-plan.ts");
}
const { classifyConflict, collapseStacks, codeFileOverlap } = lib;

const BASE = "main";
const today = process.argv[2] || new Date().toISOString().slice(0, 10);

const git = (...args) =>
  execFileSync("git", args, { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 }).trim();

const allBranches = git("for-each-ref", "--format=%(refname:short)", "refs/heads/")
  .split("\n")
  .filter((b) => b && b !== BASE);

// Build BranchInfo for branches that are NOT already merged into main.
const branches = [];
for (const name of allBranches) {
  // skip if already merged (head is ancestor of main)
  try {
    execFileSync("git", ["merge-base", "--is-ancestor", name, BASE]);
    continue; // exit 0 => merged
  } catch {
    /* not merged -> keep */
  }
  const head = git("rev-parse", name);
  const ownCommits = new Set(
    git("rev-list", `${BASE}..${name}`).split("\n").filter(Boolean),
  );
  const files = git("diff", "--name-only", `${BASE}...${name}`).split("\n").filter(Boolean);
  const [, ahead] = git("rev-list", "--left-right", "--count", `${BASE}...${name}`)
    .split(/\s+/)
    .map(Number);
  const date = git("for-each-ref", "--format=%(committerdate:short)", `refs/heads/${name}`);
  branches.push({ name, head, ownCommits, files, date, ahead });
}

const units = collapseStacks(branches);

// Trial-merge each tip into main and classify.
for (const u of units) {
  let conflictFiles = [];
  try {
    execFileSync("git", ["merge-tree", "--write-tree", "--name-only", BASE, u.tip], {
      encoding: "utf8",
    });
    // exit 0 => clean
  } catch (e) {
    // exit 1 => conflict; stdout = <tree-oid>\n<file>\n<file>...\n\n<messages>
    const out = (e.stdout || "").toString().split("\n").slice(1);
    conflictFiles = out.filter((l) => l && !l.startsWith("Auto-merging") && !l.startsWith("CONFLICT") && !l.includes(" "));
  }
  u.conflict = classifyConflict(conflictFiles);
}

const overlap = codeFileOverlap(units);

// ---- render ----
const codeUnits = units.filter((u) => u.conflict.verdict === "code");
const docUnits = units.filter((u) => u.conflict.verdict === "doc-only");
const cleanUnits = units.filter((u) => u.conflict.verdict === "clean");

const L = [];
L.push(`# Ship Plan — PA-AMZN (${today})`);
L.push("");
L.push("READ-ONLY. Generated by `scripts/ship-plan.mjs` (git-only; no merge/push/deploy).");
L.push("Regenerate any time so the merge map never goes stale.");
L.push("");
L.push("## Headline");
L.push(`- **${branches.length} unmerged branches** collapse to **${units.length} mergeable units** (tips).`);
L.push(`- Trial-merge into \`${BASE}\`: **${cleanUnits.length} clean**, **${docUnits.length} doc-only conflict** (trivial re-append), **${codeUnits.length} real code conflict**.`);
L.push(`- Code files touched by >1 unit (collision risk): **${overlap.size}**.`);
L.push("");

L.push("## Tier 1 — merge these first (clean trial-merge into main)");
L.push("Each tip subsumes its whole stack; merge the tip only. Still diff-review each.");
L.push("");
for (const u of cleanUnits) {
  L.push(`- **${u.tip}** _(ahead ${u.ahead}, ${u.date})_${u.subsumes.length ? ` — subsumes: ${u.subsumes.join(", ")}` : ""}`);
}
if (!cleanUnits.length) L.push("- _(none)_");
L.push("");

L.push("## Tier 2 — doc-only conflict (safe; only append-files collide, resolve by keeping both)");
L.push("");
for (const u of docUnits) {
  L.push(`- **${u.tip}** _(ahead ${u.ahead}, ${u.date})_ — docs: ${u.conflict.docConflicts.join(", ")}${u.subsumes.length ? ` — subsumes: ${u.subsumes.join(", ")}` : ""}`);
}
if (!docUnits.length) L.push("- _(none)_");
L.push("");

L.push("## Tier 3 — REAL code conflict (rebase / pick one lineage; do NOT merge blind)");
L.push("");
for (const u of codeUnits) {
  L.push(`- **${u.tip}** _(ahead ${u.ahead}, ${u.date})_ — code conflicts: ${u.conflict.codeConflicts.join(", ")}${u.subsumes.length ? ` — subsumes: ${u.subsumes.join(", ")}` : ""}`);
}
if (!codeUnits.length) L.push("- _(none)_");
L.push("");

L.push("## Code-file collision matrix (where independent units fight)");
L.push("Land one unit, then rebase the others onto the new main before merging.");
L.push("");
if (overlap.size === 0) {
  L.push("- _(no code file is touched by more than one unit)_");
} else {
  for (const [file, tips] of [...overlap].sort((a, b) => b[1].length - a[1].length)) {
    L.push(`- \`${file}\` — ${tips.length} units: ${tips.join(", ")}`);
  }
}
L.push("");
L.push(`_Generated ${today} from ${branches.length} unmerged branches; ${git("rev-parse", "--short", "HEAD")} on ${git("branch", "--show-current")}._`);

const outPath = `confabulator/ship-plan-${today}.md`;
writeFileSync(outPath, L.join("\n") + "\n");
console.log(`Wrote ${outPath}`);
console.log(`${branches.length} unmerged -> ${units.length} units | clean ${cleanUnits.length} / doc-only ${docUnits.length} / code ${codeUnits.length} | ${overlap.size} colliding files`);
